from server.keys import KEYS


class Config(object):
    SECRET_KEY = KEYS.SECRET_KEY
    SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{KEYS.DATABASE_USERNAME}:{KEYS.DATABASE_PASSWORD}@{KEYS.DATABASE_IP}:" \
                              f"{KEYS.DATABASE_PORT}/{KEYS.DATABASE_USERNAME}"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
