"""empty message

Revision ID: 0ea5e507528c
Revises: 
Create Date: 2020-01-07 17:17:03.508615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea5e507528c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.Column('repeat_all', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_id', sa.String(length=64), nullable=False),
    sa.Column('song_info', sa.Text(), nullable=False),
    sa.Column('playing', sa.Boolean(), nullable=True),
    sa.Column('queue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue'], ['queue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('queue')
    # ### end Alembic commands ###
