"""empty message

Revision ID: 1a0b0c2cf884
Revises: 440b4c48019a
Create Date: 2020-01-12 16:16:14.723436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a0b0c2cf884'
down_revision = '440b4c48019a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('spotify_user_db_id', sa.Integer(), nullable=True))
    op.drop_constraint('queue_ibfk_1', 'queue', type_='foreignkey')
    op.create_foreign_key(None, 'queue', 'spotify_user', ['spotify_user_db_id'], ['id'])
    op.drop_column('queue', 'spotify_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('spotify_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.create_foreign_key('queue_ibfk_1', 'queue', 'spotify_user', ['spotify_user_id'], ['id'])
    op.drop_column('queue', 'spotify_user_db_id')
    # ### end Alembic commands ###
