"""empty message

Revision ID: 30db75c260ae
Revises: 7cbfd1a44da5
Create Date: 2020-01-12 10:57:26.793842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30db75c260ae'
down_revision = '7cbfd1a44da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('devices', sa.Text(), nullable=False))
    op.alter_column('queue', 'current_song',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'current_song',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('queue', 'devices')
    # ### end Alembic commands ###
