"""empty message

Revision ID: 364af137c00d
Revises: 1a0b0c2cf884
Create Date: 2020-01-12 16:32:43.382190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '364af137c00d'
down_revision = '1a0b0c2cf884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.drop_constraint('song_ibfk_1', 'song', type_='foreignkey')
    op.create_foreign_key(None, 'song', 'queue', ['queue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('song', 'queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('queue', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.create_foreign_key('song_ibfk_1', 'song', 'queue', ['queue'], ['id'], ondelete='CASCADE')
    op.drop_column('song', 'queue_id')
    # ### end Alembic commands ###
