"""empty message

Revision ID: 7745d9c83ca4
Revises: 0ea5e507528c
Create Date: 2020-01-07 20:01:53.284029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7745d9c83ca4'
down_revision = '0ea5e507528c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotify_user', sa.Column('playback_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotify_user', 'playback_info')
    # ### end Alembic commands ###
