"""empty message

Revision ID: aced40c3d841
Revises: 364af137c00d
Create Date: 2020-01-13 16:02:48.221502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aced40c3d841'
down_revision = '364af137c00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('spotify_user_db_id', sa.Integer(), nullable=True))
    op.drop_constraint('queue_ibfk_1', 'queue', type_='foreignkey')
    op.create_foreign_key(None, 'queue', 'spotify_user', ['spotify_user_db_id'], ['id'])
    op.drop_column('queue', 'spotify_user_id')
    op.add_column('song', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.drop_constraint('song_ibfk_1', 'song', type_='foreignkey')
    op.create_foreign_key(None, 'song', 'queue', ['queue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('song', 'queue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('queue', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'song', type_='foreignkey')
    op.create_foreign_key('song_ibfk_1', 'song', 'queue', ['queue'], ['id'], ondelete='CASCADE')
    op.drop_column('song', 'queue_id')
    op.add_column('queue', sa.Column('spotify_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.create_foreign_key('queue_ibfk_1', 'queue', 'spotify_user', ['spotify_user_id'], ['id'])
    op.drop_column('queue', 'spotify_user_db_id')
    # ### end Alembic commands ###
