"""empty message

Revision ID: c4175cf399cc
Revises: b2aabf0c6a73
Create Date: 2020-01-10 12:10:49.246161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4175cf399cc'
down_revision = 'b2aabf0c6a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('spotify_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queue', 'spotify_user', ['spotify_user_id'], ['id'])
    op.add_column('spotify_user', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'spotify_user', 'queue', ['queue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_user', type_='foreignkey')
    op.drop_column('spotify_user', 'queue_id')
    op.drop_constraint(None, 'queue', type_='foreignkey')
    op.drop_column('queue', 'spotify_user_id')
    # ### end Alembic commands ###
