version: "3"
services:

  # The database container
  mysql:
    env_file:
      - database.env
    container_name: spotify_database
    build: mysql
    restart: always

  # The flask container in which the app runs
  flask:
    env_file:
      - flask.env
      - database.env

    environment:
      - DATABASE_IP=mysql

    container_name: spotify_flask
    restart: always
    build: flask
    expose:
      - 5555

  # The server that hosts the files
  nginx:
    container_name: spotify_nginx
    restart: always
    build: nginx
    ports:
      - "8080:8080"